# typed: false
# frozen_string_literal: true

# This file is autogenerated. DO NOT EDIT.
class Hoop < Formula
  desc "Hoop allows acessing any infra-structure resource easily and secure."
  homepage "https://github.com/hoophq/hoop"
  version "1.52.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.hoop.dev/release/1.52.2/hoop_1.52.2_Darwin_amd64.tar.gz"
      sha256 "351dbf79118a7d6831028cd5fbe086d8d470a0315e9db583b6b732cd5b79202d"

      def install
        bin.install "hoop"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.hoop.dev/release/1.52.2/hoop_1.52.2_Darwin_arm64.tar.gz"
      sha256 "531a1a0bf960f3087b0816e3f73ec528eb5a98bcbd96e30a97b20928957a37f3"

      def install
        bin.install "hoop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.hoop.dev/release/1.52.2/hoop_1.52.2_Linux_arm64.tar.gz"
      sha256 "3e6ab46d297a2b6aeb3a8f4d4f615cab03980dbae6c8f6ff02093bf916af4db2"

      def install
        bin.install "hoop"
      end
    end
    if Hardware::CPU.intel?
      url "https://releases.hoop.dev/release/1.52.2/hoop_1.52.2_Linux_amd64.tar.gz"
      sha256 "ecdc18380692d6a9eecf1b166ec9a5f5b83899284948311a9ac9e232e74da771"

      def install
        bin.install "hoop"
      end
    end
  end
end
