# typed: false
# frozen_string_literal: true

# This file is autogenerated. DO NOT EDIT.
class Hsh < Formula
  desc "Hoop Shell Plugins - seamless access to infrastructure via shell integration"
  homepage "https://github.com/hoophq/hsh"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hoophq/hsh/releases/download/v0.1.0/hsh-darwin-arm64"
      sha256 "aee7b03534868c53c293202b571999331a2eae9c56dffa1c49c3d5dbc97e5d16"

      def install
        bin.install "hsh-darwin-arm64" => "hsh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hoophq/hsh/releases/download/v0.1.0/hsh-darwin-x64"
      sha256 "7fea267b279bd9ffeea4134a69bd5f106b77c35b81d311453fcc0973d81cd643"

      def install
        bin.install "hsh-darwin-x64" => "hsh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoophq/hsh/releases/download/v0.1.0/hsh-linux-arm64"
      sha256 "92be9dd8a0d4eb87dccd724cb4a157f7e10c68fa1789979bdcf388138a168749"

      def install
        bin.install "hsh-linux-arm64" => "hsh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hoophq/hsh/releases/download/v0.1.0/hsh-linux-x64"
      sha256 "4b988481334ed15d6b54b9e8d76e495e0bbb207bf197b3aa0f50854e77e85578"

      def install
        bin.install "hsh-linux-x64" => "hsh"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hsh --version")
  end
end
