# typed: false
# frozen_string_literal: true

# This file is autogenerated. DO NOT EDIT.
class Hsh < Formula
  desc "Hoop Shell Plugins - seamless access to infrastructure via shell integration"
  homepage "https://github.com/hoophq/hsh"
  version "0.3.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hoophq/hsh/releases/download/v0.3.2/hsh-darwin-arm64.tar.gz"
      sha256 "875833e82920f9ff9f6c6d354f4d94f240df39447cb5f5f25604da3d111623f8"

      def install
        bin.install "hsh"
        bin.install "hsh-tunneld"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hoophq/hsh/releases/download/v0.3.2/hsh-darwin-x64.tar.gz"
      sha256 "e905cd2be71be1b5927652bf1176b0b346db1f03d7f28e7fb6890817ece744c1"

      def install
        bin.install "hsh"
        bin.install "hsh-tunneld"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoophq/hsh/releases/download/v0.3.2/hsh-linux-arm64.tar.gz"
      sha256 "ba0f7e62dadcf4bc8848739e9937dae8cd7fb8437557cd898344cc5824973b26"

      def install
        bin.install "hsh"
        bin.install "hsh-tunneld"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hoophq/hsh/releases/download/v0.3.2/hsh-linux-x64.tar.gz"
      sha256 "bcf46ffb3ae114b71c5d90aaf01c2e1bf3aaa4de98e5bee1749dbdc9cfb51fe4"

      def install
        bin.install "hsh"
        bin.install "hsh-tunneld"
      end
    end
  end

  def caveats
    <<~EOS
      hsh and hsh-tunneld are now on your PATH.

      To run the tunnel daemon as a system service, install it with
      elevated privileges (sets up a systemd unit on Linux / LaunchDaemon
      on macOS):

        sudo hsh-tunneld install

      To remove the service later:

        sudo hsh-tunneld uninstall
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hsh --version")
  end
end
