# typed: false
# frozen_string_literal: true

# This file is autogenerated. DO NOT EDIT.
class Hsh < Formula
  desc "Hoop Shell Plugins - seamless access to infrastructure via shell integration"
  homepage "https://github.com/hoophq/hsh"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hoophq/hsh/releases/download/v0.3.1/hsh-darwin-arm64.tar.gz"
      sha256 "4f3b92c676b52ef2e5d55b597687585e8253d012bf1803f95041c3056c7b7ce7"

      def install
        bin.install "hsh"
        bin.install "hsh-tunneld"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hoophq/hsh/releases/download/v0.3.1/hsh-darwin-x64.tar.gz"
      sha256 "f16437a49fb92cf683fe3bb335c33af7d62114c71ad7baf56fa9451978017141"

      def install
        bin.install "hsh"
        bin.install "hsh-tunneld"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoophq/hsh/releases/download/v0.3.1/hsh-linux-arm64.tar.gz"
      sha256 "5c590d1091c1b5987b0a9f9531063e457d02f92bc149385794e7145dc785ec43"

      def install
        bin.install "hsh"
        bin.install "hsh-tunneld"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hoophq/hsh/releases/download/v0.3.1/hsh-linux-x64.tar.gz"
      sha256 "aad283d574b77468e5e7d276cc2d327c19c75c68545425eb09d0f518b300152f"

      def install
        bin.install "hsh"
        bin.install "hsh-tunneld"
      end
    end
  end

  def caveats
    <<~EOS
      hsh and hsh-tunneld are now on your PATH.

      To run the tunnel daemon as a system service, install it with
      elevated privileges (sets up a systemd unit on Linux / LaunchDaemon
      on macOS):

        sudo hsh-tunneld install

      To remove the service later:

        sudo hsh-tunneld uninstall
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hsh --version")
  end
end
