#!/bin/bash
# Generate hsh.rb Homebrew formula from a hsh GitHub Release.
#
# Usage:
#   ./scripts/hsh-recipe.sh <version>
#
# Where <version> is the semver string WITHOUT the leading 'v' (e.g. 0.1.0).
# The script downloads SHA256SUMS from
#   https://github.com/hoophq/hsh/releases/download/v<version>/SHA256SUMS
# extracts the per-platform checksums, and emits a hsh.rb formula that points
# at the same release's binary assets.
#
# Unlike hoop (which ships tar.gz archives via releases.hoop.dev), hsh ships
# raw Bun-compiled binaries directly from GitHub Releases. The formula uses
# `bin.install <binary> => "hsh"` to rename the platform-specific binary on
# install so the user always gets `hsh` in $PATH.

set -euox pipefail

: "${1:? Missing version! $0 <version>}"
VERSION=$1
TAG="v${VERSION}"
BASE_URL="https://github.com/hoophq/hsh/releases/download/${TAG}"

mkdir -p ./dist
curl -fsSL "${BASE_URL}/SHA256SUMS" -o ./dist/hsh-checksums.txt

# Extract checksums. The SHA256SUMS file is the standard `sha256sum`
# format: `<hex-digest>  <filename>` (two spaces between digest and name).
DARWIN_ARM64_CHECKSUM=$(awk '$2 == "hsh-darwin-arm64"  {print $1}' ./dist/hsh-checksums.txt)
DARWIN_X64_CHECKSUM=$(awk   '$2 == "hsh-darwin-x64"    {print $1}' ./dist/hsh-checksums.txt)
LINUX_ARM64_CHECKSUM=$(awk  '$2 == "hsh-linux-arm64"   {print $1}' ./dist/hsh-checksums.txt)
LINUX_X64_CHECKSUM=$(awk    '$2 == "hsh-linux-x64"     {print $1}' ./dist/hsh-checksums.txt)

# Sanity-check: every platform we reference in the formula must have a
# checksum, otherwise brew install will fail with a confusing error.
for var in DARWIN_ARM64_CHECKSUM DARWIN_X64_CHECKSUM LINUX_ARM64_CHECKSUM LINUX_X64_CHECKSUM; do
  if [ -z "${!var}" ]; then
    echo "ERROR: missing checksum for ${var} in SHA256SUMS" >&2
    cat ./dist/hsh-checksums.txt >&2
    exit 1
  fi
done

cat - > hsh.rb <<EOF
# typed: false
# frozen_string_literal: true

# This file is autogenerated. DO NOT EDIT.
class Hsh < Formula
  desc "Hoop Shell Plugins - seamless access to infrastructure via shell integration"
  homepage "https://github.com/hoophq/hsh"
  version "$VERSION"

  on_macos do
    if Hardware::CPU.arm?
      url "${BASE_URL}/hsh-darwin-arm64"
      sha256 "$DARWIN_ARM64_CHECKSUM"

      def install
        bin.install "hsh-darwin-arm64" => "hsh"
      end
    end
    if Hardware::CPU.intel?
      url "${BASE_URL}/hsh-darwin-x64"
      sha256 "$DARWIN_X64_CHECKSUM"

      def install
        bin.install "hsh-darwin-x64" => "hsh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "${BASE_URL}/hsh-linux-arm64"
      sha256 "$LINUX_ARM64_CHECKSUM"

      def install
        bin.install "hsh-linux-arm64" => "hsh"
      end
    end
    if Hardware::CPU.intel?
      url "${BASE_URL}/hsh-linux-x64"
      sha256 "$LINUX_X64_CHECKSUM"

      def install
        bin.install "hsh-linux-x64" => "hsh"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hsh --version")
  end
end
EOF

echo "Generated hsh.rb for hsh ${VERSION}:"
cat hsh.rb
